"""Baseline schema (spec §4.2): profiles, games, play_sessions,
wishlist_items, follows.

Generated by autogenerate, then hand-reviewed against the spec SQL. Notable
adjustments:

- CREATE EXTENSION for citext and pg_trgm added up front. On hosted Supabase
  these are enabled via the dashboard (Database → Extensions); IF NOT EXISTS
  makes the statements no-ops there, so the same migration runs everywhere.
- profiles.id deliberately has NO foreign key to auth.users yet, although the
  spec declares one. Phase 1 seeds a placeholder Robert profile with no
  corresponding auth user; a Phase 2 migration adds the FK after the seed
  data is re-parented to the real auth.users row.

Revision ID: fe5fe4c238ae
Revises:
Create Date: 2026-07-19
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "fe5fe4c238ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # citext: case-insensitive usernames; pg_trgm: fuzzy user search indexes.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", postgresql.CITEXT(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        # ::text cast: citext's ~ matches case-insensitively, which would
        # defeat the lowercase-only charset.
        sa.CheckConstraint(
            "username::text ~ '^[a-z0-9][a-z0-9_-]{2,29}$'",
            name=op.f("ck_profiles_username_format"),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_profiles"),
        sa.UniqueConstraint("username", name="uq_profiles_username"),
    )
    # pg_trgm GIN indexes for fuzzy user search (spec §4.2).
    op.create_index(
        "ix_profiles_username_trgm",
        "profiles",
        ["username"],
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_profiles_display_name_trgm",
        "profiles",
        ["display_name"],
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )

    op.create_table(
        "games",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("system", sa.Text(), nullable=False),
        sa.Column("rating", sa.Text(), nullable=True),  # NULL = unrated
        sa.Column(
            "genres", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("igdb_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating IN ('Perfect','Great','Good','Okay','Bad')", name=op.f("ck_games_rating")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name="fk_games_user_id_profiles", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_games"),
        # Same dedupe rule the CSV implies: one entry per (owner, name, system).
        sa.UniqueConstraint("user_id", "name", "system", name="uq_games_user_id_name_system"),
    )

    op.create_table(
        "play_sessions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),  # NULL = currently playing
        # CASCADE: deleting a game takes its play history with it.
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name="fk_play_sessions_game_id_games", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_play_sessions"),
    )

    op.create_table(
        "wishlist_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("system", sa.Text(), nullable=True),
        sa.Column(
            "genres", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("igdb_id", sa.Integer(), nullable=True),
        sa.Column("starred", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("date_added", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["profiles.id"], name="fk_wishlist_items_user_id_profiles",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_wishlist_items"),
        # Wishlist dedupe is by name alone — no system in the key.
        sa.UniqueConstraint("user_id", "name", name="uq_wishlist_items_user_id_name"),
    )

    op.create_table(
        "follows",
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("followee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("follower_id <> followee_id", name=op.f("ck_follows_no_self_follow")),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["profiles.id"], name="fk_follows_follower_id_profiles",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["followee_id"], ["profiles.id"], name="fk_follows_followee_id_profiles",
            ondelete="CASCADE",
        ),
        # Composite PK: one edge per pair; duplicate follows impossible.
        sa.PrimaryKeyConstraint("follower_id", "followee_id", name="pk_follows"),
    )


def downgrade() -> None:
    # Children before parents (FK order). Indexes drop with their tables.
    op.drop_table("play_sessions")
    op.drop_table("follows")
    op.drop_table("games")
    op.drop_table("wishlist_items")
    op.drop_table("profiles")
    # citext / pg_trgm are left installed: extensions are shared database
    # state, not owned by this migration — on Supabase they're managed via
    # the dashboard, and dropping them could break objects outside public.
